import { Navbar } from '@/components/Navbar';
import Footer from '../components/Footer';

import './globals.css';
import Link from 'next/link';

export const metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-gray-100 text-gray-900">
        <Navbar/>
        {/* Main Content */}
        <main>
          {children}
        </main>
         <Footer/>
      </body>
    </html>
  );
}
