import { Navbar } from "@/components/Navbar";
import Footer from "../components/Footer";
import open_Sans from "next/font/google";
// const opensans = Open_sans({ subsets: ['latin'] });
import { Open_Sans } from "next/font/google";
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // optional, pick what you need
});
import "./globals.css";
// import Link from 'next/link';
// import Homepage from './home/page';

export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} bg-gray-100 text-gray-900 basicTheme`}
      >
        <Navbar />

        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
