import { Navbar } from "@/components/Navbar";
import Footer from "../components/Footer";
// import open_Sans from "next/font/google";
// const opensans = Open_sans({ subsets: ['latin'] });
import { Open_Sans } from "next/font/google";
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], 
  variable: "--font-open-sans"
});
import "./globals.css";
// import Link from 'next/link';
// import Homepage from './home/page';

export const metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={openSans.className}>
      <body
        className={` basicTheme font-sans`}
      >
        <div className=" !text-[var(--color-dark)]">

        <Navbar />
        </div>

        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
